checks:
    similar-code:
        enabled: false
    identical-code:
        enabled: false
    method-lines:
        enabled: true
        config:
        threshold: 40

    exclude_patterns:
    - "**/test/"
    - "**/androidTest/"
    - "**test"
